cp ../rename_Exon_v1/about-us.php .
cp ../rename_Exon_v1/academy.php .
cp ../rename_Exon_v1/account.php .
cp ../rename_Exon_v1/blog.php .
cp ../rename_Exon_v1/blog1.php .
cp ../rename_Exon_v1/business-growth.php .
cp ../rename_Exon_v1/careers.php .
cp ../rename_Exon_v1/projects.php .
cp ../rename_Exon_v1/refund-policy.php .
cp ../rename_Exon_v1/seo-search.php .
cp ../rename_Exon_v1/services.php .
cp ../rename_Exon_v1/sitemap.php .
cp ../rename_Exon_v1/softwares.php .
cp ../rename_Exon_v1/startup-workspace-connect.php .
cp ../rename_Exon_v1/cloud.php .
cp ../rename_Exon_v1/company.php .
cp ../rename_Exon_v1/connect-co-working-space.php .
cp ../rename_Exon_v1/consultancy.php .
cp ../rename_Exon_v1/contact.php .
cp ../rename_Exon_v1/council.php .
cp ../rename_Exon_v1/coworking-space.php .
cp ../rename_Exon_v1/development.php .
cp ../rename_Exon_v1/digital-marketing.php .
cp ../rename_Exon_v1/disclaimer.php .
cp ../rename_Exon_v1/events.php .
cp ../rename_Exon_v1/events1.php .
cp ../rename_Exon_v1/faq.php .
cp ../rename_Exon_v1/footer.php .
cp ../rename_Exon_v1/header.php .
cp ../rename_Exon_v1/index.php .
cp ../rename_Exon_v1/industries.php .
cp ../rename_Exon_v1/Internship-In-Vellore.php .
cp ../rename_Exon_v1/internships.php .
cp ../rename_Exon_v1/jobs.php .
cp ../rename_Exon_v1/law-firm.php .
cp ../rename_Exon_v1/news.php .
cp ../rename_Exon_v1/news1.php .
cp ../rename_Exon_v1/news2.php .
cp ../rename_Exon_v1/news3.php .
cp ../rename_Exon_v1/news4.php .
cp ../rename_Exon_v1/online-payment.php .
cp ../rename_Exon_v1/partners.php .
cp ../rename_Exon_v1/partners1.php .
cp ../rename_Exon_v1/privacy-policy.php .
cp ../rename_Exon_v1/privacypolicy.php .
cp ../rename_Exon_v1/project.php .
mkdir -p cloud && cp ../rename_Exon_v1/cloud/about-redbackcloud-vellore.php "$_"
mkdir -p cloud && cp ../rename_Exon_v1/cloud/about.php "$_"
mkdir -p cloud && cp ../rename_Exon_v1/cloud/blog.php "$_"
mkdir -p cloud && cp ../rename_Exon_v1/cloud/business-email.php "$_"
mkdir -p cloud && cp ../rename_Exon_v1/cloud/cloud-hosting.php "$_"
mkdir -p cloud && cp ../rename_Exon_v1/cloud/codeguard.php "$_"
mkdir -p cloud && cp ../rename_Exon_v1/cloud/contact-us.php "$_"
mkdir -p cloud && cp ../rename_Exon_v1/cloud/dedicated-servers.php "$_"
mkdir -p cloud && cp ../rename_Exon_v1/cloud/domain-price.php "$_"
mkdir -p cloud && cp ../rename_Exon_v1/cloud/domain-promos.php "$_"
mkdir -p cloud && cp ../rename_Exon_v1/cloud/enterprise-email.php "$_"
mkdir -p cloud && cp ../rename_Exon_v1/cloud/faqs.php "$_"
mkdir -p cloud && cp ../rename_Exon_v1/cloud/footer.php "$_"
mkdir -p cloud && cp ../rename_Exon_v1/cloud/google-apps.php "$_"
mkdir -p cloud && cp ../rename_Exon_v1/cloud/login.php "$_"
mkdir -p cloud && cp ../rename_Exon_v1/cloud/register-domain.php "$_"
mkdir -p cloud && cp ../rename_Exon_v1/cloud/reseller-hosting.php "$_"
mkdir -p cloud && cp ../rename_Exon_v1/cloud/services.php "$_"
mkdir -p cloud && cp ../rename_Exon_v1/cloud/support.php "$_"
mkdir -p cloud && cp ../rename_Exon_v1/cloud/testimonials.php "$_"
mkdir -p cloud && cp ../rename_Exon_v1/cloud/transfer-domain.php "$_"
mkdir -p cloud && cp ../rename_Exon_v1/cloud/vps.php "$_"
mkdir -p cloud && cp ../rename_Exon_v1/cloud/wordpress-hosting.php "$_"
mkdir -p consultancy && cp ../rename_Exon_v1/consultancy/about-us.php "$_"
mkdir -p consultancy && cp ../rename_Exon_v1/consultancy/business-consulting.php "$_"
mkdir -p consultancy && cp ../rename_Exon_v1/consultancy/career.php "$_"
mkdir -p consultancy && cp ../rename_Exon_v1/consultancy/clients.php "$_"
mkdir -p consultancy && cp ../rename_Exon_v1/consultancy/company.php "$_"
mkdir -p consultancy && cp ../rename_Exon_v1/consultancy/contact-email.php "$_"
mkdir -p consultancy && cp ../rename_Exon_v1/consultancy/contact.php "$_"
mkdir -p consultancy && cp ../rename_Exon_v1/consultancy/faq.php "$_"
mkdir -p consultancy && cp ../rename_Exon_v1/consultancy/footer.php "$_"
mkdir -p consultancy && cp ../rename_Exon_v1/consultancy/header.php "$_"
mkdir -p consultancy && cp ../rename_Exon_v1/consultancy/HR-Consulting.php "$_"
mkdir -p consultancy && cp ../rename_Exon_v1/consultancy/index.php "$_"
mkdir -p consultancy && cp ../rename_Exon_v1/consultancy/industry.php "$_"
mkdir -p consultancy && cp ../rename_Exon_v1/consultancy/ISO-Consulting.php "$_"
mkdir -p consultancy && cp ../rename_Exon_v1/consultancy/IT-Consulting.php "$_"
mkdir -p consultancy && cp ../rename_Exon_v1/consultancy/legal-consulting.php "$_"
mkdir -p consultancy && cp ../rename_Exon_v1/consultancy/marketing-consultant.php "$_"
mkdir -p consultancy && cp ../rename_Exon_v1/consultancy/services.php "$_"
mkdir -p consultancy && cp ../rename_Exon_v1/consultancy/team.php "$_"
mkdir -p consultancy && cp ../rename_Exon_v1/consultancy/technolgy-consultant.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/about-us.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/aeronautical-projects.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/all.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/android-projects.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/artificial-intelligence-projects.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/automobiles-projects.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/bio-medical-projects.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/bio-metrics-projects.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/blog-2.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/blog.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/cad-modeling-projects.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/cae-structural-projects.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/cae-thermal-projects.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/careers.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/case-studies.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/case-study-details.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/cfd-analysis-projects.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/cloud-computing-projects.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/company-history.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/company-overview.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/contact-2.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/contact-3.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/contact.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/dot-net-projects.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/elements.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/embedded-projects.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/faq.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/faqs.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/footer.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/gallery.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/gsm-gps-projects.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/ieee-android.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/ieee-bigdata.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/ieee-embedded-systems.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/ieee-java.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/ieee-matlab.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/ieee-ns2.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/ieee-oracle.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/ieee-powerelectronics.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/ieee.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/image-processing-projects.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/ind-productivity-projects.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/index-5.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/information-security-projects.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/index.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/inplant-training.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/internship.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/ios-projects.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/java.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/journal-paper-projects.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/matlab-projects.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/mech-production-projects.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/mechatronics-projects.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/miniprojects-electronics.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/miniprojects.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/our-approach.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/our-partners.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/our-team.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/php-projects.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/plc-projects.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/Pneumatic-projects.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/portfolio-2-column.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/portfolio-3-column.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/portfolio-layout-2-2-column.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/portfolio-layout-2.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/portfolio-layout-3-2-column.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/portfolio-layout-3.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/portfolio-masonry-2-column.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/portfolio-masonry.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/pricing.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/privacy-policy.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/projects.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/research-development.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/robotics-projects.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/seo-update.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/services-layout-2.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/services-layout-3.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/services.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/single-service-2.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/single-service.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/smart-card-projects.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/solar-wind-projects.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/team-member.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/testimonials.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/thermal-projects.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/tt.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/vacancy-details.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/web-based-projects.php "$_"
mkdir -p projects && cp ../rename_Exon_v1/projects/zigbee-rfid-projects.php "$_"
mkdir -p projects/freelancer && cp ../rename_Exon_v1/projects/freelancer/billing.php "$_"
mkdir -p projects/freelancer && cp ../rename_Exon_v1/projects/freelancer/completedprojects.php "$_"
mkdir -p projects/freelancer && cp ../rename_Exon_v1/projects/freelancer/dashboard.php "$_"
mkdir -p projects/freelancer && cp ../rename_Exon_v1/projects/freelancer/profile.php "$_"
mkdir -p projects/freelancer && cp ../rename_Exon_v1/projects/freelancer/projects.php "$_"
mkdir -p projects/freelancer && cp ../rename_Exon_v1/projects/freelancer/registration.php "$_"
mkdir -p projects/ieee-projects && cp ../rename_Exon_v1/projects/ieee-projects/all.php "$_"
mkdir -p projects/ieee-projects && cp ../rename_Exon_v1/projects/ieee-projects/android-project.php "$_"
mkdir -p projects/ieee-projects && cp ../rename_Exon_v1/projects/ieee-projects/android.php "$_"
mkdir -p projects/ieee-projects && cp ../rename_Exon_v1/projects/ieee-projects/big-data.php "$_"
mkdir -p projects/ieee-projects && cp ../rename_Exon_v1/projects/ieee-projects/dot-net-project.php "$_"
mkdir -p projects/ieee-projects && cp ../rename_Exon_v1/projects/ieee-projects/dot-net.php "$_"
mkdir -p projects/ieee-projects && cp ../rename_Exon_v1/projects/ieee-projects/embedded-systems.php "$_"
mkdir -p projects/ieee-projects && cp ../rename_Exon_v1/projects/ieee-projects/index.php "$_"
mkdir -p projects/ieee-projects && cp ../rename_Exon_v1/projects/ieee-projects/java-project.php "$_"
mkdir -p projects/ieee-projects && cp ../rename_Exon_v1/projects/ieee-projects/java.php "$_"
mkdir -p projects/ieee-projects && cp ../rename_Exon_v1/projects/ieee-projects/matlab.php "$_"
mkdir -p projects/ieee-projects && cp ../rename_Exon_v1/projects/ieee-projects/ns2.php "$_"
mkdir -p projects/ieee-projects && cp ../rename_Exon_v1/projects/ieee-projects/oracle.php "$_"
mkdir -p projects/ieee-projects && cp ../rename_Exon_v1/projects/ieee-projects/php-project.php "$_"
mkdir -p projects/ieee-projects && cp ../rename_Exon_v1/projects/ieee-projects/power-electronics.php "$_"
mkdir -p projects/ieee-projects && cp ../rename_Exon_v1/projects/ieee-projects/testing.php "$_"
mkdir -p projects/ieee-projects && cp ../rename_Exon_v1/projects/ieee-testing.php "$_"
mkdir -p projects/partner && cp ../rename_Exon_v1/projects/partner/addproject.php "$_"
mkdir -p projects/partner && cp ../rename_Exon_v1/projects/partner/adduser.php "$_"
mkdir -p projects/partner && cp ../rename_Exon_v1/projects/partner/dashboard.php "$_"
mkdir -p projects/partner && cp ../rename_Exon_v1/projects/partner/profile.php "$_"
mkdir -p projects/partner && cp ../rename_Exon_v1/projects/partner/registration.php "$_"
mkdir -p projects/trail/admin && cp ../rename_Exon_v1/projects/trail/admin/blog.php "$_"
mkdir -p projects/trail/admin && cp ../rename_Exon_v1/projects/trail/admin/cal.php "$_"
mkdir -p projects/trail/admin && cp ../rename_Exon_v1/projects/trail/admin/cart.php "$_"
mkdir -p studios/bpo && cp ../rename_Exon_v1/studios/bpo/index.php "$_"
mkdir -p studios/clients && cp ../rename_Exon_v1/studios/clients/index.php "$_"
mkdir -p studios && cp ../rename_Exon_v1/studios/contact.php "$_"
mkdir -p studios && cp ../rename_Exon_v1/studios/fmenu.php "$_"
mkdir -p studios && cp ../rename_Exon_v1/studios/header.php "$_"
mkdir -p studios && cp ../rename_Exon_v1/studios/hmenu.php "$_"
mkdir -p studios && cp ../rename_Exon_v1/studios/index.php "$_"
mkdir -p studios && cp ../rename_Exon_v1/studios/portfolio.php "$_"
mkdir -p studios/digital-marketing && cp ../rename_Exon_v1/studios/digital-marketing/index.php "$_"
mkdir -p studios/domain-registration && cp ../rename_Exon_v1/studios/domain-registration/index.php "$_"
mkdir -p studios/web-hosting && cp ../rename_Exon_v1/studios/web-hosting/index.php "$_"
mkdir -p studios/website-development && cp ../rename_Exon_v1/studios/website-development/index.php "$_"
cp ../rename_Exon_v1/studios.php .
cp ../rename_Exon_v1/sustainability.php .
mkdir -p systems && cp ../rename_Exon_v1/systems/about.php "$_"
mkdir -p systems && cp ../rename_Exon_v1/systems/backup-recovery-vellore.php "$_"
mkdir -p systems && cp ../rename_Exon_v1/systems/backup-recovery.php "$_"
mkdir -p systems && cp ../rename_Exon_v1/systems/biometric.php "$_"
mkdir -p systems && cp ../rename_Exon_v1/systems/careers.php "$_"
mkdir -p systems && cp ../rename_Exon_v1/systems/cctv-camera.php "$_"
mkdir -p systems/computer-services && cp ../rename_Exon_v1/systems/computer-services/ambur.php "$_"
mkdir -p systems/computer-services && cp ../rename_Exon_v1/systems/computer-services/arakkonam.php "$_"
mkdir -p systems/computer-services && cp ../rename_Exon_v1/systems/computer-services/arani.php "$_"
mkdir -p systems/computer-services && cp ../rename_Exon_v1/systems/computer-services/arcot.php "$_"
mkdir -p systems/computer-services && cp ../rename_Exon_v1/systems/computer-services/chennai.php "$_"
mkdir -p systems/computer-services && cp ../rename_Exon_v1/systems/computer-services/chittoor.php "$_"
mkdir -p systems/computer-services && cp ../rename_Exon_v1/systems/computer-services/gudiyatham.php "$_"
mkdir -p systems/computer-services && cp ../rename_Exon_v1/systems/computer-services/index.php "$_"
mkdir -p systems/computer-services && cp ../rename_Exon_v1/systems/computer-services/kanchipuram.php "$_"
mkdir -p systems/computer-services && cp ../rename_Exon_v1/systems/computer-services/krishnagiri.php "$_"
mkdir -p systems/computer-services && cp ../rename_Exon_v1/systems/computer-services/ranipet.php "$_"
mkdir -p systems/computer-services && cp ../rename_Exon_v1/systems/computer-services/sholinghur.php "$_"
mkdir -p systems/computer-services && cp ../rename_Exon_v1/systems/computer-services/sriperumbudur.php "$_"
mkdir -p systems/computer-services && cp ../rename_Exon_v1/systems/computer-services/tambram.php "$_"
mkdir -p systems/computer-services && cp ../rename_Exon_v1/systems/computer-services/thiruvannamalai.php "$_"
mkdir -p systems/computer-services && cp ../rename_Exon_v1/systems/computer-services/tirupattur.php "$_"
mkdir -p systems/computer-services && cp ../rename_Exon_v1/systems/computer-services/tiruvallur.php "$_"
mkdir -p systems/computer-services && cp ../rename_Exon_v1/systems/computer-services/vaniyambadi.php "$_"
mkdir -p systems/computer-services && cp ../rename_Exon_v1/systems/computer-services/vellore.php "$_"
mkdir -p systems/computer-services && cp ../rename_Exon_v1/systems/computer-services/walajapet.php "$_"
mkdir -p systems && cp ../rename_Exon_v1/systems/computer-support.php "$_"
mkdir -p systems && cp ../rename_Exon_v1/systems/contact.php "$_"
mkdir -p systems && cp ../rename_Exon_v1/systems/daas.php "$_"
mkdir -p systems && cp ../rename_Exon_v1/systems/email-solutions.php "$_"
mkdir -p systems && cp ../rename_Exon_v1/systems/exincorp-systems-remote-support.php "$_"
mkdir -p systems && cp ../rename_Exon_v1/systems/faq.php "$_"
mkdir -p systems && cp ../rename_Exon_v1/systems/footer.php "$_"
mkdir -p systems && cp ../rename_Exon_v1/systems/gallery.php "$_"
mkdir -p systems && cp ../rename_Exon_v1/systems/header.php "$_"
mkdir -p systems && cp ../rename_Exon_v1/systems/iaas.php "$_"
mkdir -p systems && cp ../rename_Exon_v1/systems/index.php "$_"
mkdir -p systems && cp ../rename_Exon_v1/systems/it-consulting.php "$_"
mkdir -p systems && cp ../rename_Exon_v1/systems/partners.php "$_"
mkdir -p systems && cp ../rename_Exon_v1/systems/payment.php "$_"
mkdir -p systems && cp ../rename_Exon_v1/systems/philosophy.php "$_"
mkdir -p systems && cp ../rename_Exon_v1/systems/phone-solutions.php "$_"
mkdir -p systems && cp ../rename_Exon_v1/systems/servers.php "$_"
mkdir -p systems && cp ../rename_Exon_v1/systems/services.php "$_"
mkdir -p systems && cp ../rename_Exon_v1/systems/site-map.php "$_"
mkdir -p systems && cp ../rename_Exon_v1/systems/sitemap.php "$_"
mkdir -p systems && cp ../rename_Exon_v1/systems/support-managed-services.php "$_"
mkdir -p systems && cp ../rename_Exon_v1/systems/testimonial.php "$_"
mkdir -p systems && cp ../rename_Exon_v1/systems/values.php "$_"
mkdir -p systems && cp ../rename_Exon_v1/systems/web-protection.php "$_"
cp ../rename_Exon_v1/systems.php .
cp ../rename_Exon_v1/team.php .
cp ../rename_Exon_v1/terms-and-conditions.php .
cp ../rename_Exon_v1/testimonial.php .
